[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { workspace = true }
validator = { workspace = true }
strum = { workspace = true }
num_enum = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
